### ISSUE TITLE
want support for node v6.12.0

### ISSUE THREAD

**Issue by misterdjules** [joyent/node-fast#12]
It seems that node-fast doesn't support node v6.12.0:

```
➜  node-fast git:(master) ✗ node --version 
v6.12.0
➜  node-fast git:(master) ✗ npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> dtrace-provider@0.8.5 install /Users/JulienGilli/dev/sdc/node-fast/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js


> dtrace-provider@0.6.0 install /Users/JulienGilli/dev/sdc/node-fast/node_modules/dtrace-provider
> node scripts/install.js


> dtrace-provider@0.8.5 install /Users/JulienGilli/dev/sdc/node-fast/node_modules/restify/node_modules/dtrace-provider
> node scripts/install.js


> microtime@2.0.0 install /Users/JulienGilli/dev/sdc/node-fast/node_modules/microtime
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/microtime/src/microtime.o
In file included from ../src/microtime.cc:9:
In file included from ../node_modules/nan/nan.h:182:
../node_modules/nan/nan_maybe_43_inl.h:221:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/JulienGilli/.node-gyp/6.12.0/include/node/v8.h:3032:36: note: 'CloneElementAt' has been explicitly marked deprecated here
                MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                   ^
/Users/JulienGilli/.node-gyp/6.12.0/include/node/v8config.h:336:3: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/microtime.cc:9:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/JulienGilli/.node-gyp/6.12.0/include/node/v8.h:4009:56: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
/Users/JulienGilli/.node-gyp/6.12.0/include/node/v8config.h:336:3: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/microtime.cc:9:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:1927:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/JulienGilli/.node-gyp/6.12.0/include/node/v8.h:2751:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<Name> name,
                     ^
/Users/JulienGilli/.node-gyp/6.12.0/include/node/v8config.h:336:3: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
3 warnings and 4 errors generated.
make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/JulienGilli/.nvm/versions/node/v6.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/Users/JulienGilli/.nvm/versions/node/v6.12.0/bin/node" "/Users/JulienGilli/.nvm/versions/node/v6.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/JulienGilli/dev/sdc/node-fast/node_modules/microtime
gyp ERR! node -v v6.12.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
fast@2.3.1 /Users/JulienGilli/dev/sdc/node-fast
├─┬ artedi@1.1.1 
│ └─┬ jsprim@1.4.0 
│   ├── extsprintf@1.0.2 
│   └── verror@1.3.6 
├── assert-plus@1.0.0 
├─┬ bunyan@1.8.12 
│ ├── dtrace-provider@0.8.5 
│ ├── moment@2.19.2 
│ ├─┬ mv@2.1.1 
│ │ ├─┬ mkdirp@0.5.1 
│ │ │ └── minimist@0.0.8 
│ │ ├── ncp@2.0.0 
│ │ └─┬ rimraf@2.4.5 
│ │   └─┬ glob@6.0.4 
│ │     ├── inflight@1.0.6 
│ │     ├─┬ minimatch@3.0.4 
│ │     │ └─┬ brace-expansion@1.1.8 
│ │     │   ├── balanced-match@1.0.0 
│ │     │   └── concat-map@0.0.1 
│ │     └── path-is-absolute@1.0.1 
│ └── safe-json-stringify@1.0.4 
├─┬ cmdutil@1.1.0 
│ └── assert-plus@0.1.5 
├── crc@0.3.0 
├─┬ dtrace-provider@0.6.0 
│ └── nan@2.8.0 
├── extsprintf@1.3.0 
├── forkexec@1.1.0 
├─┬ jsprim@1.4.1 
│ └── json-schema@0.2.3 
├─┬ kang@1.2.0 
│ └─┬ restify-clients@1.1.1 
│   ├── assert-plus@0.1.5 
│   ├─┬ backoff@2.5.0 
│   │ └── precond@0.2.3 
│   ├── keep-alive-agent@0.0.1 
│   ├── lodash@3.10.1 
│   ├── lru-cache@2.7.3 
│   ├── node-uuid@1.4.8 
│   ├─┬ restify-errors@3.1.0 
│   │ └── assert-plus@0.2.0 
│   ├── semver@5.4.1 
│   └── tunnel-agent@0.4.3 
├─┬ lstream@0.0.4 
│ └─┬ readable-stream@2.3.3 
│   ├── inherits@2.0.3 
│   ├── isarray@1.0.0 
│   ├── process-nextick-args@1.0.7 
│   ├── safe-buffer@5.1.1 
│   ├── string_decoder@1.0.3 
│   └── util-deprecate@1.0.2 
├── posix-getopt@1.2.0 
├─┬ restify@5.2.0 
│ ├─┬ clone-regexp@1.0.0 
│ │ ├── is-regexp@1.0.0 
│ │ └── is-supported-regexp-flag@1.0.0 
│ ├─┬ csv@1.2.1 
│ │ ├── csv-generate@1.1.2 
│ │ ├── csv-parse@1.3.3 
│ │ ├─┬ csv-stringify@1.1.2 
│ │ │ └── lodash.get@4.4.2 
│ │ └── stream-transform@0.2.2 
│ ├── dtrace-provider@0.8.5 
│ ├── escape-regexp-component@1.0.2 
│ ├── formidable@1.1.1 
│ ├─┬ http-signature@1.2.0 
│ │ └─┬ sshpk@1.13.1 
│ │   ├── asn1@0.2.3 
│ │   ├── bcrypt-pbkdf@1.0.1 
│ │   ├── dashdash@1.14.1 
│ │   ├── ecc-jsbn@0.1.1 
│ │   ├── getpass@0.1.7 
│ │   ├── jsbn@0.1.1 
│ │   └── tweetnacl@0.14.5 
│ ├── lodash@4.17.4 
│ ├─┬ lru-cache@4.1.1 
│ │ ├── pseudomap@1.0.2 
│ │ └── yallist@2.1.2 
│ ├── mime@1.4.1 
│ ├── negotiator@0.6.1 
│ ├─┬ once@1.4.0 
│ │ └── wrappy@1.0.2 
│ ├── qs@6.5.1 
│ ├── restify-errors@4.3.0 
│ ├── semver@5.4.1 
│ ├─┬ spdy@3.4.7 
│ │ ├─┬ debug@2.6.9 
│ │ │ └── ms@2.0.0 
│ │ ├── handle-thing@1.2.5 
│ │ ├── http-deceiver@1.2.7 
│ │ ├── select-hose@2.0.0 
│ │ └─┬ spdy-transport@2.0.20 
│ │   ├── detect-node@2.0.3 
│ │   ├── hpack.js@2.1.6 
│ │   ├── obuf@1.1.1 
│ │   └─┬ wbuf@1.7.2 
│ │     └── minimalistic-assert@1.0.0 
│ └── uuid@3.1.0 
├── strsplit@1.0.0 
├─┬ vasync@1.6.4 
│ └─┬ verror@1.6.0 
│   └── extsprintf@1.2.0 
└─┬ verror@1.10.0 
  └── core-util-is@1.0.2 

npm ERR! Darwin 13.4.0
npm ERR! argv "/Users/JulienGilli/.nvm/versions/node/v6.12.0/bin/node" "/Users/JulienGilli/.nvm/versions/node/v6.12.0/bin/npm" "install"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! microtime@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the microtime@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs microtime
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/JulienGilli/dev/sdc/node-fast/npm-debug.log
➜  node-fast git:(master) ✗
```

It seems that just updating the `microtime` dependency to its latest version fixes this problem without introducing any disruptive change. I'll submit a change asap to fix this.

**Comment by misterdjules** [comment]
Testing notes for https://cr.joyent.us/#/c/2949/:

```
➜  node-fast git:(fix-issue-12) ✗ nvm install v6.12.0                                                   
v6.12.0 is already installed.
Now using node v6.12.0 (npm v3.10.10)
➜  node-fast git:(fix-issue-12) ✗ rm -rf node_modules 
➜  node-fast git:(fix-issue-12) ✗ npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> dtrace-provider@0.8.5 install /Users/JulienGilli/dev/sdc/node-fast/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js


> dtrace-provider@0.6.0 install /Users/JulienGilli/dev/sdc/node-fast/node_modules/dtrace-provider
> node scripts/install.js


> dtrace-provider@0.8.5 install /Users/JulienGilli/dev/sdc/node-fast/node_modules/restify/node_modules/dtrace-provider
> node scripts/install.js


> microtime@2.1.6 install /Users/JulienGilli/dev/sdc/node-fast/node_modules/microtime
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/microtime-v2.1.6-node-v48-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/JulienGilli/.npm/_prebuilds/https-github.com-wadey-node-microtime-releases-download-v2.1.6-microtime-v2.1.6-node-v48-darwin-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /Users/JulienGilli/.npm/_prebuilds/https-github.com-wadey-node-microtime-releases-download-v2.1.6-microtime-v2.1.6-node-v48-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/JulienGilli/dev/sdc/node-fast/node_modules/microtime/build/Release/microtime.node
prebuild-install info unpack required /Users/JulienGilli/dev/sdc/node-fast/node_modules/microtime/build/Release/microtime.node successfully
prebuild-install info install Successfully installed prebuilt binary!
fast@2.3.1 /Users/JulienGilli/dev/sdc/node-fast
├─┬ artedi@1.1.1 
│ └─┬ jsprim@1.4.0 
│   ├── extsprintf@1.0.2 
│   └── verror@1.3.6 
├── assert-plus@1.0.0 
├─┬ bunyan@1.8.12 
│ ├── dtrace-provider@0.8.5 
│ ├── moment@2.19.2 
│ ├─┬ mv@2.1.1 
│ │ ├─┬ mkdirp@0.5.1 
│ │ │ └── minimist@0.0.8 
│ │ ├── ncp@2.0.0 
│ │ └─┬ rimraf@2.4.5 
│ │   └─┬ glob@6.0.4 
│ │     ├── inflight@1.0.6 
│ │     ├─┬ minimatch@3.0.4 
│ │     │ └─┬ brace-expansion@1.1.8 
│ │     │   ├── balanced-match@1.0.0 
│ │     │   └── concat-map@0.0.1 
│ │     └── path-is-absolute@1.0.1 
│ └── safe-json-stringify@1.0.4 
├─┬ cmdutil@1.1.0 
│ └── assert-plus@0.1.5 
├── crc@0.3.0 
├─┬ dtrace-provider@0.6.0 
│ └── nan@2.8.0 
├── extsprintf@1.3.0 
├── forkexec@1.1.0 
├─┬ jsprim@1.4.1 
│ └── json-schema@0.2.3 
├─┬ kang@1.2.0 
│ └─┬ restify-clients@1.1.1 
│   ├── assert-plus@0.1.5 
│   ├─┬ backoff@2.5.0 
│   │ └── precond@0.2.3 
│   ├── keep-alive-agent@0.0.1 
│   ├── lodash@3.10.1 
│   ├── lru-cache@2.7.3 
│   ├── node-uuid@1.4.8 
│   ├─┬ restify-errors@3.1.0 
│   │ └── assert-plus@0.2.0 
│   ├── semver@5.4.1 
│   └── tunnel-agent@0.4.3 
├─┬ lstream@0.0.4 
│ └─┬ readable-stream@2.3.3 
│   ├── inherits@2.0.3 
│   ├── isarray@1.0.0 
│   ├── process-nextick-args@1.0.7 
│   ├── safe-buffer@5.1.1 
│   ├── string_decoder@1.0.3 
│   └── util-deprecate@1.0.2 
├─┬ microtime@2.1.6 
│ ├── bindings@1.2.1 
│ ├── nan@2.6.2 
│ └─┬ prebuild-install@2.3.0 
│   ├── expand-template@1.1.0 
│   ├── github-from-package@0.0.0 
│   ├── minimist@1.2.0 
│   ├─┬ node-abi@2.1.2 
│   │ └── semver@5.4.1 
│   ├── noop-logger@0.1.1 
│   ├─┬ npmlog@4.1.2 
│   │ ├─┬ are-we-there-yet@1.1.4 
│   │ │ └── delegates@1.0.0 
│   │ ├── console-control-strings@1.1.0 
│   │ ├─┬ gauge@2.7.4 
│   │ │ ├── aproba@1.2.0 
│   │ │ ├── has-unicode@2.0.1 
│   │ │ ├── object-assign@4.1.1 
│   │ │ ├── signal-exit@3.0.2 
│   │ │ ├─┬ string-width@1.0.2 
│   │ │ │ ├── code-point-at@1.1.0 
│   │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
│   │ │ │   └── number-is-nan@1.0.1 
│   │ │ ├─┬ strip-ansi@3.0.1 
│   │ │ │ └── ansi-regex@2.1.1 
│   │ │ └── wide-align@1.1.2 
│   │ └── set-blocking@2.0.0 
│   ├── os-homedir@1.0.2 
│   ├─┬ pump@1.0.2 
│   │ └── end-of-stream@1.4.0 
│   ├─┬ rc@1.2.2 
│   │ ├── deep-extend@0.4.2 
│   │ ├── ini@1.3.4 
│   │ ├── minimist@1.2.0 
│   │ └── strip-json-comments@2.0.1 
│   ├─┬ simple-get@1.4.3 
│   │ └── unzip-response@1.0.2 
│   ├─┬ tar-fs@1.16.0 
│   │ ├── chownr@1.0.1 
│   │ └─┬ tar-stream@1.5.5 
│   │   └── bl@1.2.1 
│   ├── tunnel-agent@0.6.0 
│   └── xtend@4.0.1 
├── posix-getopt@1.2.0 
├─┬ restify@5.2.0 
│ ├─┬ clone-regexp@1.0.0 
│ │ ├── is-regexp@1.0.0 
│ │ └── is-supported-regexp-flag@1.0.0 
│ ├─┬ csv@1.2.1 
│ │ ├── csv-generate@1.1.2 
│ │ ├── csv-parse@1.3.3 
│ │ ├─┬ csv-stringify@1.1.2 
│ │ │ └── lodash.get@4.4.2 
│ │ └── stream-transform@0.2.2 
│ ├── dtrace-provider@0.8.5 
│ ├── escape-regexp-component@1.0.2 
│ ├── formidable@1.1.1 
│ ├─┬ http-signature@1.2.0 
│ │ └─┬ sshpk@1.13.1 
│ │   ├── asn1@0.2.3 
│ │   ├── bcrypt-pbkdf@1.0.1 
│ │   ├── dashdash@1.14.1 
│ │   ├── ecc-jsbn@0.1.1 
│ │   ├── getpass@0.1.7 
│ │   ├── jsbn@0.1.1 
│ │   └── tweetnacl@0.14.5 
│ ├── lodash@4.17.4 
│ ├─┬ lru-cache@4.1.1 
│ │ ├── pseudomap@1.0.2 
│ │ └── yallist@2.1.2 
│ ├── mime@1.4.1 
│ ├── negotiator@0.6.1 
│ ├─┬ once@1.4.0 
│ │ └── wrappy@1.0.2 
│ ├── qs@6.5.1 
│ ├── restify-errors@4.3.0 
│ ├── semver@5.4.1 
│ ├─┬ spdy@3.4.7 
│ │ ├─┬ debug@2.6.9 
│ │ │ └── ms@2.0.0 
│ │ ├── handle-thing@1.2.5 
│ │ ├── http-deceiver@1.2.7 
│ │ ├── select-hose@2.0.0 
│ │ └─┬ spdy-transport@2.0.20 
│ │   ├── detect-node@2.0.3 
│ │   ├── hpack.js@2.1.6 
│ │   ├── obuf@1.1.1 
│ │   └─┬ wbuf@1.7.2 
│ │     └── minimalistic-assert@1.0.0 
│ └── uuid@3.1.0 
├── strsplit@1.0.0 
├─┬ vasync@1.6.4 
│ └─┬ verror@1.6.0 
│   └── extsprintf@1.2.0 
└─┬ verror@1.10.0 
  └── core-util-is@1.0.2 

➜  node-fast git:(fix-issue-12) ✗ make test
deps/catest/catest test/tst.allocator.js test/tst.client_generic.js test/tst.client_request.js test/tst.protocol_decoder.js test/tst.protocol_encoder.js test/tst.server.js test/tst.socket_summarize.js
Configuration:
    SRC:                         /Users/JulienGilli/dev/sdc/node-fast
    Output directory:            /var/tmp/catest.27143
    Temp directory:              /var/tmp/catest.27143_tmpfiles
    Keep successful test output: false
    Found 7 test(s) to run

===================================================

Executing test test/tst.allocator.js ... success.
Executing test test/tst.client_generic.js ... success.
Executing test test/tst.client_request.js ... success.
Executing test test/tst.protocol_decoder.js ... success.
Executing test test/tst.protocol_encoder.js ... success.
Executing test test/tst.server.js ... success.
Executing test test/tst.socket_summarize.js ... success.

===================================================

Results:
	Tests passed:	 7/ 7
	Tests failed:	 0/ 7

===================================================
Cleaning up output from successful tests ... done.
Note: Compatibility tests need to be run manually with "make test-compat".
➜  node-fast git:(fix-issue-12) ✗
```

I also checked that the `microtime` module did not make any significant change to its behavior or API. From version 2.0.0 to 2.1.6, it basically just updated its use of NAN to be compatible with more recent V8 versions.

**Comment by davepacheco** [comment]
Can we close this issue?

**Comment by misterdjules** [comment]
Yes, sorry for not closing it before!
